# Web Scraping Lab

You will find in this notebook some scrapy exercises to practise your scraping skills.

**Tips:**

- Check the response status code for each request to ensure you have obtained the intended content.
- Print the response text in each request to understand the kind of info you are getting and its format.
- Check for patterns in the response text to extract the data/info requested in each question.
- Visit the urls below and take a look at their source code through Chrome DevTools. You'll need to identify the html tags, special class names, etc used in the html content you are expected to extract.

**Resources**:
- [Requests library](http://docs.python-requests.org/en/master/#the-user-guide)
- [Beautiful Soup Doc](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Urllib](https://docs.python.org/3/library/urllib.html#module-urllib)
- [re lib](https://docs.python.org/3/library/re.html)
- [lxml lib](https://lxml.de/)
- [Scrapy](https://scrapy.org/)
- [List of HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)
- [HTML basics](http://www.simplehtmlguide.com/cheatsheet.php)
- [CSS basics](https://www.cssbasics.com/#page_start)

#### Below are the libraries and modules you may need. `requests`,  `BeautifulSoup` and `pandas` are already imported for you. If you prefer to use additional libraries feel free to do it.

In [28]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import numpy as np
import datetime
from pandas.io.json import json_normalize

#### Download, parse (using BeautifulSoup), and print the content from the Trending Developers page from GitHub:

In [29]:
# This is the url you will scrape in this exercise
url = 'https://github.com/trending/developers'

In [30]:
# your code here
html = requests.get(url).content
soup = BeautifulSoup(html, "lxml")

#### 1. Display the names of the trending developers retrieved in the previous step.

Your output should be a Python list of developer names. Each name should not contain any html tag.

**Instructions:**

1. Find out the html tag and class names used for the developer names. You can achieve this using Chrome DevTools or clicking in 'Inspect' on any browser. Here is an example:

![title](example_1.png)

2. Use BeautifulSoup `find_all()` to extract all the html elements that contain the developer names. Hint: pass in the `attrs` parameter to specify the class.

3. Loop through the elements found and get the text for each of them.

4. While you are at it, use string manipulation techniques to replace whitespaces and linebreaks (i.e. `\n`) in the *text* of each html element. Use a list to store the clean names. Hint: you may also use `.get_text()` instead of `.text` and pass in the desired parameters to do some string manipulation (check the documentation).

5. Print the list of names.

Your output should look like below:

```
['trimstray (@trimstray)',
 'joewalnes (JoeWalnes)',
 'charlax (Charles-AxelDein)',
 'ForrestKnight (ForrestKnight)',
 'revery-ui (revery-ui)',
 'alibaba (Alibaba)',
 'Microsoft (Microsoft)',
 'github (GitHub)',
 'facebook (Facebook)',
 'boazsegev (Bo)',
 'google (Google)',
 'cloudfetch',
 'sindresorhus (SindreSorhus)',
 'tensorflow',
 'apache (TheApacheSoftwareFoundation)',
 'DevonCrawford (DevonCrawford)',
 'ARMmbed (ArmMbed)',
 'vuejs (vuejs)',
 'fastai (fast.ai)',
 'QiShaoXuan (Qi)',
 'joelparkerhenderson (JoelParkerHenderson)',
 'torvalds (LinusTorvalds)',
 'CyC2018',
 'komeiji-satori (神楽坂覚々)',
 'script-8']
 ```

In [31]:
# your code here
'''
I have one doubt here: I am proposing this code because it looks simple and efficient but I am not sure whether it achieves the desired outcome.
Thus, some of the class names are not aligned with the html tag.
'''
names = [soup.find_all(class_='h3 lh-condensed')[i].get_text(strip=True) + ' '+'(' + 
         soup.find_all('p',{'class':'f4 text-normal mb-1'})[i].get_text(strip=True) + ')' for i in range(0,24)]
names

['Márk Sági-Kazár (sagikazarmark)',
 'Michele Locati (mlocati)',
 'Frank Denis (jedisct1)',
 'Lipis (lipis)',
 'William Durand (willdurand)',
 'Dawid Urbaniak (Trancever)',
 'Alexey Pyltsyn (lex111)',
 'Ian Storm Taylor (ianstormtaylor)',
 'Stephen Celis (stephencelis)',
 'Francois Zaninotto (fzaninotto)',
 'PySimpleGUI (PySimpleGUI)',
 'Toni de la Fuente (toniblyx)',
 'Jake Vanderplas (jakevdp)',
 'Stefan Prodan (stefanprodan)',
 'chriseth (normanmaurer)',
 'Norman Maurer (miekg)',
 'Miek Gieben (stsrki)',
 'Mladen Macanović (nschloe)',
 'Nico Schlömer (arvidn)',
 'Arvid Norberg (eamodio)',
 'Eric Amodio (driesvints)',
 'Dries Vints (nicolaskruchten)',
 'Nicolas Kruchten (bernd)',
 'Bernd Ahlers (mrdoob)']

In [32]:
'''
Therefore, I have tried a different way:
'''
text = soup.find_all('div',{'class':'col-md-6'})
'''
 I noticed that using the 'div' may lead to the inclusion of additional things that would need to be removed.
'''
clean_text = []
found = False
for elements in text:
    for string in elements:
         if str(string).find('"TRENDING_DEVELOPER"') != -1:
            clean_text.append(elements)
            break
'''
 After the above, we would need to parse the data. 
 This seems aligned with the content of the website. Please, kindly refer to the last update of the code and printing of the page.
'''
username = []
for i in range(len(clean_text)):
    username_parse = [element.strip() for element in clean_text[i].get_text().split("\n") if element != '']
    if len(username_parse) > 2:
        username.append(username_parse[0] + " (" + username_parse[2] + ")")
    else:
        username.append(username_parse[0])
        
username

['Márk Sági-Kazár (sagikazarmark)',
 'Michele Locati (mlocati)',
 'Frank Denis (jedisct1)',
 'Lipis (lipis)',
 'William Durand (willdurand)',
 'Dawid Urbaniak (Trancever)',
 'Alexey Pyltsyn (lex111)',
 'Ian Storm Taylor (ianstormtaylor)',
 'Stephen Celis (stephencelis)',
 'Francois Zaninotto (fzaninotto)',
 'PySimpleGUI (PySimpleGUI)',
 'Toni de la Fuente (toniblyx)',
 'Jake Vanderplas (jakevdp)',
 'Stefan Prodan (stefanprodan)',
 'chriseth',
 'Norman Maurer (normanmaurer)',
 'Miek Gieben (miekg)',
 'Mladen Macanović (stsrki)',
 'Nico Schlömer (nschloe)',
 'Arvid Norberg (arvidn)',
 'Eric Amodio (eamodio)',
 'Dries Vints (driesvints)',
 'Nicolas Kruchten (nicolaskruchten)',
 'Bernd Ahlers (bernd)',
 'Mr.doob (mrdoob)']

#### 1.1. Display the trending Python repositories in GitHub.

The steps to solve this problem is similar to the previous one except that you need to find out the repository names instead of developer names.

In [33]:
# This is the url you will scrape in this exercise
url = 'https://github.com/trending/python?since=daily'

In [34]:
# your code here
html = requests.get(url).content
soup = BeautifulSoup(html, "lxml")

In [36]:
text = soup.find_all('h1',{'class':"h3 lh-condensed"})
text[0].get_text()

srg_repos = []
for i in range(len(text)):
    srg_repos_parse = [element.strip() for element in text[i].get_text().replace("/","").split("\n") if element != '']
    srg_repos.append(srg_repos_parse[0] + " (" + srg_repos_parse[1] + ")")

srg_repos

['carlospolop (hacktricks)',
 'dagster-io (dagster)',
 'django (django)',
 'almarklein (timetagger)',
 'mtlynch (tinypilot)',
 'public-apis (public-apis)',
 'DingXiaoH (RepVGG)',
 'minimaxir (big-list-of-naughty-strings)',
 'huggingface (transformers)',
 'confluentinc (confluent-kafka-python)',
 'JDAI-CV (FaceX-Zoo)',
 'Trusted-AI (adversarial-robustness-toolbox)',
 'tiangolo (fastapi)',
 'ddbourgin (numpy-ml)',
 'psf (black)',
 'hodcroftlab (covariants)',
 'locustio (locust)',
 'owid (covid-19-data)',
 'NVIDIA (apex)',
 'faif (python-patterns)',
 'd0nk (parler-tricks)',
 'spack (spack)',
 'scikit-learn (scikit-learn)',
 'python-poetry (poetry)',
 'SeanPedersen (HyperTag)']

#### 2. Display all the image links from Walt Disney wikipedia page.
Hint: use `.get()` to access information inside tags. Check out the documentation.

In [37]:
# This is the url you will scrape in this exercise
url = 'https://en.wikipedia.org/wiki/Walt_Disney'

In [38]:
# your code here
html = requests.get(url).content
soup = BeautifulSoup(html, "lxml")

images = []
for img in soup.findAll('img'):
    images.append(img.get('src'))

images

['//upload.wikimedia.org/wikipedia/en/thumb/e/e7/Cscr-featured.svg/20px-Cscr-featured.svg.png',
 '//upload.wikimedia.org/wikipedia/en/thumb/8/8c/Extended-protection-shackle.svg/20px-Extended-protection-shackle.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/d/df/Walt_Disney_1946.JPG/220px-Walt_Disney_1946.JPG',
 '//upload.wikimedia.org/wikipedia/commons/thumb/8/87/Walt_Disney_1942_signature.svg/150px-Walt_Disney_1942_signature.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Walt_Disney_envelope_ca._1921.jpg/220px-Walt_Disney_envelope_ca._1921.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Newman_Laugh-O-Gram_%281921%29.webm/220px-seek%3D2-Newman_Laugh-O-Gram_%281921%29.webm.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Trolley_Troubles_poster.jpg/170px-Trolley_Troubles_poster.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/7/71/Walt_Disney_and_his_cartoon_creation_%22Mickey_Mouse%22_-_National_Board_of_Review_Magazine.jpg/170px-Walt_Disney_and_his_cartoon_creation_%22Mickey_Mouse%22_-_National_Board_of_Review_Magazine.jpg',
 '//upload.wikimedia.org/wikipedia/en/thumb/4/4e/Steamboat-willie.jpg/170px-Steamboat-willie.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/5/57/Walt_Disney_1935.jpg/170px-Walt_Disney_1935.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Walt_Disney_Snow_white_1937_trailer_screenshot_%2813%29.jpg/220px-Walt_Disney_Snow_white_1937_trailer_screenshot_%2813%29.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/1/15/Disney_drawing_goofy.jpg/170px-Disney_drawing_goofy.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/1/13/DisneySchiphol1951.jpg/220px-DisneySchiphol1951.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/8/8c/WaltDisneyplansDisneylandDec1954.jpg/220px-WaltDisneyplansDisneylandDec1954.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Walt_disney_portrait_right.jpg/170px-Walt_disney_portrait_right.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Walt_Disney_Grave.JPG/170px-Walt_Disney_Grave.JPG',
 '//upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Roy_O._Disney_with_Company_at_Press_Conference.jpg/170px-Roy_O._Disney_with_Company_at_Press_Conference.jpg',
 '//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Disney_Display_Case.JPG/170px-Disney_Display_Case.JPG',
 '//upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Disney1968.jpg/170px-Disney1968.jpg',
 '//upload.wikimedia.org/wikipedia/en/thumb/8/8a/OOjs_UI_icon_edit-ltr-progressive.svg/10px-OOjs_UI_icon_edit-ltr-progressive.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/d/da/Animation_disc.svg/30px-Animation_disc.svg.png',
 '//upload.wikimedia.org/wikipedia/en/thumb/6/69/P_vip.svg/29px-P_vip.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Magic_Kingdom_castle.jpg/24px-Magic_Kingdom_castle.jpg',
 '//upload.wikimedia.org/wikipedia/en/thumb/e/e7/Video-x-generic.svg/30px-Video-x-generic.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Flag_of_Los_Angeles_County%2C_California.svg/30px-Flag_of_Los_Angeles_County%2C_California.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Blank_television_set.svg/30px-Blank_television_set.svg.png',
 '//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/30px-Flag_of_the_United_States.svg.png',
 '//upload.wikimedia.org/wikipedia/en/thumb/4/4a/Commons-logo.svg/22px-Commons-logo.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Wikiquote-logo.svg/25px-Wikiquote-logo.svg.png',
 '//upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Wikidata-logo.svg/30px-Wikidata-logo.svg.png',
 '//upload.wikimedia.org/wikipedia/en/thumb/8/8a/OOjs_UI_icon_edit-ltr-progressive.svg/10px-OOjs_UI_icon_edit-ltr-progressive.svg.png',
 '//en.wikipedia.org/wiki/Special:CentralAutoLogin/start?type=1x1',
 '/static/images/footer/wikimedia-button.png',
 '/static/images/footer/poweredby_mediawiki_88x31.png']

#### 2.1. List all language names and number of related articles in the order they appear in wikipedia.org.

In [39]:
# This is the url you will scrape in this exercise
url = 'https://www.wikipedia.org/'

In [40]:
# your code here
html = requests.get(url).content
soup = BeautifulSoup(html, "lxml")

count_language_box = soup.find_all(class_= 'central-featured-lang')
len(count_language_box)

count_language_box = [soup.find_all(class_= 'central-featured-lang')[i].get_text().replace('+','').replace('\xa0',',').replace('\n\n','') for i in range(0,len(count_language_box))]
count_language_box

['English\n6,226,000 articles',
 '日本語\n1,247,000 記事',
 'Deutsch\n2,522,000 Artikel',
 'Español\n1,652,000 artículos',
 'Русский\n1,690,000 статей',
 'Français\n2,287,000 articles',
 'Italiano\n1,665,000 voci',
 '中文\n1,169,000 條目',
 'Português\n1,051,000 artigos',
 'Polski\n1,448,000 haseł']

#### 2.2. Display the top 10 languages by number of native speakers stored in a pandas dataframe.
Hint: After finding the correct table you want to analyse, you can use a nested **for** loop to find the elements row by row (check out the 'td' and 'tr' tags). <br>An easier way to do it is using pd.read_html(), check out documentation [here](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.read_html.html).

In [65]:
# This is the url you will scrape in this exercise
url = 'https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers'

In [68]:
# your code here
data = pd.read_html(url)
data
#Not sure why it is not presenting the dataframe...

[    0                                                  1
 0 NaN  This section needs to be updated. Please updat...,
     Rank                            Language  Speakers(millions)  \
 0      1                    Mandarin Chinese               918.0
 1      2                             Spanish               480.0
 2      3                             English               379.0
 3      4  Hindi (sanskritised Hindustani)[9]               341.0
 4      5                             Bengali               228.0
 ..   ...                                 ...                 ...
 86    87                               Czech                10.7
 87    88                Taʽizzi-Adeni Arabic                10.5
 88    89                              Uyghur                10.4
 89    90                    Min Dong Chinese                10.3
 90    91                             Sylheti                10.3

    Percentageof world pop.(March 2019)[8] Language family        Branch
 0                                 11.922%    Sino-Tibetan       Sinitic
 1                                  5.994%   Indo-European       Romance
 2                                  4.922%   Indo-European      Germanic
 3                                  4.429%   Indo-European    Indo-Aryan
 4                                  2.961%   Indo-European    Indo-Aryan
 ..                                    ...             ...           ...
 86                                 0.139%   Indo-European  Balto-Slavic
 87                                 0.136%     Afroasiatic       Semitic
 88                                 0.135%          Turkic        Karluk
 89                                 0.134%    Sino-Tibetan       Sinitic
 90                                 0.134%   Indo-European    Indo-Aryan

 [91 rows x 6 columns],
     0                                                  1
 0 NaN  This section needs to be updated. The reason g...,
       Rank                  Language Nativespeakersin millions2007 (2010)  \
 0        1  Mandarin (entire branch)                            935 (955)
 1        2                   Spanish                            390 (405)
 2        3                   English                            365 (360)
 3        4                  Hindi[a]                            295 (310)
 4        5                    Arabic                            280 (295)
 ..     ...                       ...                                  ...
 96      97                     Xhosa                                  7.6
 97      98                Belarusian                               7.6[d]
 98      99                   Balochi                                  7.6
 99     100                   Konkani                                  7.4
 100  Total                       NaN                                 5610

     Percentageof worldpopulation(2007)
 0                                14.1%
 1                                5.85%
 2                                5.52%
 3                                4.46%
 4                                4.23%
 ..                                 ...
 96                               0.11%
 97                               0.11%
 98                               0.11%
 99                               0.11%
 100                                85%

 [101 rows x 4 columns],
    .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}.mw-parser-output .infobox .navbar{font-size:100%}.mw-parser-output .navbox .navbar{display:block;font-size:100%}.mw-parser-output .navbox-title .navbar{float:left;text-align:left;margin-right:0.5em}vteCountries and languages lists  \
 0   CountriesBy languagesSpoken Countries by spoke...
 1                                           Countries
 2   By languagesSpoken Countries by spoken languag...
 3                                        By languages
 4                                              Spoken
 5                                            Official
 6                                            Endonyms
 7                                             Exonyms
 8   LanguagesBy continent Africa Americas North So...
 9                                           Languages
 10  By continent Africa Americas North South Asia ...
 11                                       By continent
 12                                         By country
 13                                      By population
 14                                          By family
 15            Language-basedgeopoliticalorganizations
 16                                           See also

    .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}.mw-parser-output .infobox .navbar{font-size:100%}.mw-parser-output .navbox .navbar{display:block;font-size:100%}.mw-parser-output .navbox-title .navbar{float:left;text-align:left;margin-right:0.5em}vteCountries and languages lists.1
 0   CountriesBy languagesSpoken Countries by spoke...
 1                                           Countries
 2   By languagesSpoken Countries by spoken languag...
 3   Spoken Countries by spoken languages Official ...
 4                       Countries by spoken languages
 5   Countries by the number of recognized official...
 6          Countries and capitals in native languages
 7   Country names in various languages A–C D–I J–P...
 8   LanguagesBy continent Africa Americas North So...
 9                                           Languages
 10  By continent Africa Americas North South Asia ...
 11  Africa Americas North South Asia East South Eu...
 12  Official languages by state List of languages ...
 13  By number of native speakers By number of tota...
 14  Language families List of Afro-Asiatic languag...
 15  Arab League (Arabic) Dutch Language Union (Dut...
 16              Lists of languages Category:Languages                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ,
                                            Countries  \
 0  By languagesSpoken Countries by spoken languag...
 1                                       By languages
 2                                             Spoken
 3                                           Official
 4                                           Endonyms
 5                                            Exonyms

                                          Countries.1
 0  By languagesSpoken Countries by spoken languag...
 1  Spoken Countries by spoken languages Official ...
 2                      Countries by spoken languages
 3  Countries by the number of recognized official...
 4         Countries and capitals in native languages
 5  Country names in various languages A–C D–I J–P...  ,
               0                                                  1
 0  By languages  Spoken Countries by spoken languages Official ...
 1        Spoken                      Countries by spoken languages
 2      Official  Countries by the number of recognized official...
 3      Endonyms         Countries and capitals in native languages
 4       Exonyms  Country names in various languages A–C D–I J–P...,
           0                                                  1
 0    Spoken                      Countries by spoken languages
 1  Official  Countries by the number of recognized official...,
                                            Languages  \
 0  By continent Africa Americas North South Asia ...
 1                                       By continent
 2                                         By country
 3                                      By population
 4                                          By family
 5            Language-basedgeopoliticalorganizations
 6                                           See also

                                          Languages.1
 0  By continent Africa Americas North South Asia ...
 1  Africa Americas North South Asia East South Eu...
 2  Official languages by state List of languages ...
 3  By number of native speakers By number of tota...
 4  Language families List of Afro-Asiatic languag...
 5  Arab League (Arabic) Dutch Language Union (Dut...
 6              Lists of languages Category:Languages  ,
                                          0  \
 0                             By continent
 1                               By country
 2                            By population
 3                                By family
 4  Language-basedgeopoliticalorganizations
 5                                 See also

                                                    1
 0  Africa Americas North South Asia East South Eu...
 1  Official languages by state List of languages ...
 2  By number of native speakers By number of tota...
 3  Language families List of Afro-Asiatic languag...
 4  Arab League (Arabic) Dutch Language Union (Dut...
 5              Lists of languages Category:Languages  ]

In [67]:
data1 = data[0]
data1.head(10)

    0                                                  1
0 NaN  This section needs to be updated. Please updat...

#### 3. Display IMDB's top 250 data (movie name, initial release, director name and stars) as a pandas dataframe.
Hint: If you hover over the title of the movie, you should see the director's name. Can you find where it's stored in the html?

In [83]:
# This is the url you will scrape in this exercise 
url = 'https://www.imdb.com/chart/top'

In [87]:
# your code here
import numpy as np

In [88]:
response = requests.get(url).content
soup = BeautifulSoup(response, 'lxml')

directors = soup.find_all('td',attrs = {'class':'titleColumn'})[0]
directors.find('a').get('title')

'Frank Darabont (dir.), Tim Robbins, Morgan Freeman'

In [94]:
col_title = soup.select('td.titleColumn')
directors = [str(col_title[i]).split('title=')[1].split('(dir.)')[0].replace('"','').strip() for i in range(len(col_title))]
directors = pd.DataFrame(directors)

In [95]:
data = pd.read_html(url)[0]
data['Director Name'] = directors

In [96]:
def get_year_imdb(my_string):
    return int(re.findall('\d\d\d\d',my_string)[0])

def get_title_imdb(my_string):
    regex_string = re.findall('[^. (\d)]+',my_string)
    return " ".join(regex_string)

In [97]:
data['Initial Release'] = list(map(get_year_imdb,data['Rank & Title']))
data['Title'] = list(map(get_title_imdb,data['Rank & Title']))

In [98]:
data = data.drop(['Your Rating','Unnamed: 4','Unnamed: 0','Rank & Title'],axis=1)

In [99]:
data = data[['Title', 'Initial Release', 'Director Name', 'IMDb Rating']]
data

,Title,Initial Release,Director Name,IMDb Rating
0,The Shawshank Redemption,1994,Frank Darabont,9.2
1,The Godfather,1972,Francis Ford Coppola,9.1
2,The Godfather: Part II,1974,Francis Ford Coppola,9.0
3,The Dark Knight,2008,Christopher Nolan,9.0
4,Angry Men,1957,Sidney Lumet,8.9
...,...,...,...,...
245,Drishyam,2015,Nishikant Kamat,8.0
246,Shin seiki Evangelion Gekijô-ban: Air/Magokoro...,1997,Hideaki Anno,8.0
247,La battaglia di Algeri,1966,Gillo Pontecorvo,8.0
248,The Princess Bride,1987,Rob Reiner,8.0
249,Mandariinid,2013,Zaza Urushadze,8.0

#### 3.1. Display the movie name, year and a brief summary of the top 10 random movies (IMDB) as a pandas dataframe.

In [77]:
#This is the url you will scrape in this exercise
url = 'https://www.imdb.com/list/ls009796553/'
response = requests.get(url).content
soup = BeautifulSoup(response, 'lxml')

In [101]:
my_class_lister_item_header = soup.find_all('h3',attrs = {'class':'lister-item-header'})[:10]
my_unnamed_class = soup.find_all("p", {"class":""})[:10]

In [102]:
movie_names_and_years = [my_class_lister_item_header[i].get_text().replace('\n',"") for i in range(len(my_class_lister_item_header))]
movie_year = list(map(get_year_imdb,movie_names_and_years))
movie_name = list(map(get_title_imdb,movie_names_and_years))

In [103]:
movie_description = [my_unnamed_class[i].get_text() for i in range(len(my_unnamed_class))]
movie_description = [movie_description[i].replace("\n","").strip() for i in range(len(movie_description))]

In [104]:
data = pd.DataFrame(list(zip(movie_name,movie_year,movie_description)),columns =['Name', 'Year', 'Description'])
data

,Name,Year,Description
0,A Nightmare on Elm Street,1984,The monstrous spirit of a slain child murderer...
1,Awakenings,1990,The victims of an encephalitis epidemic many y...
2,A League of Their Own,1992,Two sisters join the first female professional...
3,A Bronx Tale,1993,A father becomes worried when a local gangster...
4,Angels in the Outfield,1994,When a boy prays for a chance to have a family...
5,A Time to Kill,1996,"In Canton, Mississippi, a fearless young lawye..."
6,Amistad,1997,"In 1839, the revolt of Mende captives aboard a..."
7,Anaconda,1997,"A ""National Geographic"" film crew is taken hos..."
8,"A Cool, Dry Place",1998,"Russell, single father balances his work as a ..."
9,American History X,1998,A former neo-nazi skinhead tries to prevent hi...

## Bonus

#### Find the live weather report (temperature, wind speed, description and weather) of a given city.

In [105]:
#https://openweathermap.org/current
city = input('Enter the city: ')
url = 'http://api.openweathermap.org/data/2.5/weather?'+'q='+city+'&APPID=b35975e18dc93725acb092f7272cc6b8&units=metric'

Enter the city:  Luxembourg

In [106]:
# your code here
def weather(city):
    test = print(url)
    link = test
    page = requests.get(url)
    page.content
    soup = BeautifulSoup(page.content)
    converting = list(soup)
    converting2= str(page.content).split(",")
    description = converting2[4].split(":")[1].replace("'","")
    wind_Speed = converting2[14].split(":")[2]
    temperature = converting2[7].split(":")[2]
    return "Temperature: " +temperature + " Wind speed: " + wind_Speed + " Description: " + description

weather(city)

http://api.openweathermap.org/data/2.5/weather?q=Luxembourg&APPID=b35975e18dc93725acb092f7272cc6b8&units=metric

'Temperature: -2.03 Wind speed: 0.45 Description: "overcast clouds"'

#### Find the book name, price and stock availability as a pandas dataframe.

In [ ]:
# This is the url you will scrape in this exercise. 
# It is a fictional bookstore created to be scraped. 
url = 'http://books.toscrape.com/'

In [109]:
# your code here
import requests
url = 'http://books.toscrape.com/'
page = requests.get(url)
page.content
soup = BeautifulSoup(page.content)
test = list(soup.children)

In [110]:
title = [soup.find_all('h3')[i].get_text() for i in range(0,20)]

price = [soup.find_all('p',{"class":"price_color"})[i].get_text().split("\n") for i in range(0,20)]
stock = [soup.find_all('p',{"class":"instock availability"})[i].get_text().replace("\n\n    \n        ","").replace("\n    \n","") for i in range(0,20)]

price2 = [y for x in price for y in x]

In [111]:
df = pd.DataFrame()

df["Title"]= title
df["Price"]=price2
df["Stock"]=stock

df

                                    Title   Price     Stock
0                      A Light in the ...  £51.77  In stock
1                      Tipping the Velvet  £53.74  In stock
2                              Soumission  £50.10  In stock
3                           Sharp Objects  £47.82  In stock
4            Sapiens: A Brief History ...  £54.23  In stock
5                         The Requiem Red  £22.65  In stock
6            The Dirty Little Secrets ...  £33.34  In stock
7                 The Coming Woman: A ...  £17.93  In stock
8                     The Boys in the ...  £22.60  In stock
9                         The Black Maria  £52.15  In stock
10  Starving Hearts (Triangular Trade ...  £13.99  In stock
11                  Shakespeare's Sonnets  £20.66  In stock
12                            Set Me Free  £17.46  In stock
13    Scott Pilgrim's Precious Little ...  £52.29  In stock
14                      Rip it Up and ...  £35.02  In stock
15                  Our Band Could Be ...  £57.25  In stock
16                                   Olio  £23.88  In stock
17        Mesaerion: The Best Science ...  £37.59  In stock
18           Libertarianism for Beginners  £51.33  In stock
19                It's Only the Himalayas  £45.17  In stock

####  Display the 100 latest earthquakes info (date, time, latitude, longitude and region name) by the EMSC as a pandas dataframe.
***Hint:*** Here the displayed number of earthquakes per page is 20, but you can easily move to the next page by looping through the desired number of pages and adding it to the end of the url.

In [112]:
# This is the url you will scrape in this exercise
url = 'https://www.emsc-csem.org/Earthquake/?view='

# This is how you will loop through each page:
number_of_pages = int(100/20)
each_page_urls = []

for n in range(1, number_of_pages+1):
    link = url+str(n)
    each_page_urls.append(link)
    
each_page_urls

['https://www.emsc-csem.org/Earthquake/?view=1',
 'https://www.emsc-csem.org/Earthquake/?view=2',
 'https://www.emsc-csem.org/Earthquake/?view=3',
 'https://www.emsc-csem.org/Earthquake/?view=4',
 'https://www.emsc-csem.org/Earthquake/?view=5']

In [113]:
# your code here

url1 = 'https://www.emsc-csem.org/Earthquake/?view=1'
url2 = 'https://www.emsc-csem.org/Earthquake/?view=2'
url3 = 'https://www.emsc-csem.org/Earthquake/?view=3'
url4 = 'https://www.emsc-csem.org/Earthquake/?view=4'
url5 = 'https://www.emsc-csem.org/Earthquake/?view=5'
page = requests.get(url)
 
page.content

soup = BeautifulSoup(page.content)

test = list(soup.children)


data1 = pd.read_html(url1)
data2 = pd.read_html(url2)
data3 = pd.read_html(url3)
data4 = pd.read_html(url4)
data5 = pd.read_html(url5)


data_earthquaks = data1[3]

earthquakes = pd.DataFrame()

earthquakes["Dates & time"] = data_earthquaks["Date & Time UTC"]["12345678910»"]
earthquakes["Latitude"] = data_earthquaks["Latitude degrees"]["12345678910»"]
earthquakes["Latitude2"] = data_earthquaks["Latitude degrees"]["12345678910».1"]
earthquakes["Longitud"] = data_earthquaks["Longitude degrees"]["12345678910»"]
earthquakes["Longitud2"] = data_earthquaks["Longitude degrees"]["12345678910».1"]
earthquakes["Region Name"] = data_earthquaks["Last update [-]"]["12345678910»"]

In [114]:
earthquakes

,Dates & time,Latitude,Latitude2,Longitud,Longitud2,Region Name
0,2021-01-16 10:28:02.208min ago,38.94,N,43.64,E,EASTERN TURKEY
1,2021-01-16 10:18:44.017min ago,45.61,N,15.92,E,CROATIA
2,2021-01-16 09:59:30.636min ago,45.43,N,16.09,E,CROATIA
3,2021-01-16 09:56:13.839min ago,37.90,N,118.56,W,CENTRAL CALIFORNIA
4,2021-01-16 09:43:14.552min ago,37.57,N,139.68,E,"EASTERN HONSHU, JAPAN"
5,2021-01-16 09:42:30.053min ago,35.88,N,0.74,W,NORTHERN ALGERIA
6,2021-01-16 09:42:18.253min ago,30.58,S,177.08,W,"KERMADEC ISLANDS, NEW ZEALAND"
7,2021-01-16 09:31:13.21hr 04min ago,17.98,N,66.84,W,PUERTO RICO
8,2021-01-16 09:29:54.41hr 06min ago,19.17,N,155.49,W,"ISLAND OF HAWAII, HAWAII"
9,2021-01-16 09:26:45.31hr 09min ago,6.20,S,104.14,E,"SUNDA STRAIT, INDONESIA"
10,2021-01-16 09:08:06.01hr 28min ago,33.58,S,70.63,W,"REGION METROPOLITANA, CHILE"
11,2021-01-16 09:03:23.01hr 32min ago,31.02,S,71.38,W,"COQUIMBO, CHILE"
12,2021-01-16 08:57:56.71hr 38min ago,37.24,N,44.89,E,TURKEY-IRAN-IRAQ BORDER REGION
13,2021-01-16 08:48:21.31hr 47min ago,34.09,N,25.96,E,"CRETE, GREECE"
14,2021-01-16 08:41:59.01hr 54min ago,23.10,S,66.92,W,"JUJUY, ARGENTINA"
15,2021-01-16 08:30:18.12hr 05min ago,19.20,N,155.45,W,"ISLAND OF HAWAII, HAWAII"
16,2021-01-16 08:18:48.82hr 17min ago,39.11,N,37.37,E,CENTRAL TURKEY
17,2021-01-16 08:17:41.02hr 18min ago,45.47,N,15.95,E,CROATIA
18,2021-01-16 08:16:21.52hr 19min ago,43.09,N,0.20,W,PYRENEES
19,2021-01-16 08:15:35.82hr 20min ago,36.53,N,29.75,E,WESTERN TURKEY
20,2021-01-16 08:08:36.02hr 27min ago,39.53,N,142.92,E,"NEAR EAST COAST OF HONSHU, JAPAN"
21,2021-01-16 08:06:42.92hr 29min ago,19.39,N,155.27,W,"ISLAND OF HAWAII, HAWAII"
22,2021-01-16 08:03:12.22hr 32min ago,19.08,N,155.46,W,"ISLAND OF HAWAII, HAWAII"
23,2021-01-16 07:37:24.02hr 58min ago,35.65,S,71.39,W,"MAULE, CHILE"
24,2021-01-16 07:33:34.03hr 02min ago,15.62,N,93.83,W,"OFFSHORE CHIAPAS, MEXICO"
25,2021-01-16 07:30:55.03hr 05min ago,13.98,N,92.55,W,OFFSHORE GUATEMALA
26,2021-01-16 07:29:42.73hr 06min ago,37.91,N,118.56,W,CENTRAL CALIFORNIA
27,2021-01-16 07:28:15.93hr 07min ago,37.91,N,118.55,W,CENTRAL CALIFORNIA
28,2021-01-16 07:27:07.03hr 09min ago,1.27,N,79.80,W,NEAR COAST OF ECUADOR
29,2021-01-16 07:27:00.03hr 09min ago,31.02,S,71.38,W,"COQUIMBO, CHILE"
30,2021-01-16 07:22:38.73hr 13min ago,37.94,N,27.45,E,WESTERN TURKEY
31,2021-01-16 07:17:15.53hr 18min ago,37.91,N,26.93,E,"DODECANESE ISLANDS, GREECE"
32,2021-01-16 07:16:02.23hr 20min ago,37.91,N,118.56,W,CENTRAL CALIFORNIA
33,2021-01-16 07:03:36.73hr 32min ago,19.44,N,154.87,W,"HAWAII REGION, HAWAII"
34,2021-01-16 06:56:34.33hr 39min ago,37.91,N,118.56,W,CENTRAL CALIFORNIA
35,2021-01-16 06:56:06.03hr 40min ago,1.17,S,80.50,W,NEAR COAST OF ECUADOR
36,2021-01-16 06:55:27.93hr 40min ago,37.90,N,118.53,W,CENTRAL CALIFORNIA
37,2021-01-16 06:52:20.63hr 43min ago,37.94,N,118.68,W,CENTRAL CALIFORNIA
38,2021-01-16 06:42:19.03hr 53min ago,8.79,S,125.94,E,EAST TIMOR REGION
39,2021-01-16 06:41:25.93hr 54min ago,37.91,N,118.55,W,CENTRAL CALIFORNIA
40,2021-01-16 06:37:32.43hr 58min ago,5.71,S,148.80,E,"NEW BRITAIN REGION, P.N.G."
41,2021-01-16 06:36:36.53hr 59min ago,20.09,S,173.86,W,TONGA
42,2021-01-16 06:32:15.24hr 03min ago,37.90,N,118.54,W,CENTRAL CALIFORNIA
43,2021-01-16 06:28:04.04hr 08min ago,1.54,S,99.87,E,"KEP. MENTAWAI REGION, INDONESIA"
44,2021-01-16 06:27:28.44hr 08min ago,35.44,N,27.14,E,"DODECANESE ISLANDS, GREECE"
45,2021-01-16 06:23:35.04hr 12min ago,1.13,N,79.47,W,NEAR COAST OF ECUADOR
46,2021-01-16 06:13:53.04hr 22min ago,20.62,S,69.48,W,"TARAPACA, CHILE"
47,2021-01-16 06:09:31.04hr 26min ago,45.56,N,16.12,E,CROATIA
48,2021-01-16 05:53:27.04hr 42min ago,45.61,N,16.05,E,CROATIA
49,2021-01-16 05:49:14.74hr 46min ago,38.31,N,79.34,W,VIRGINIA
50,NaN,NaN,NaN,NaN,NaN,NaN
51,12345678910»,12345678910»,12345678910»,12345678910»,12345678910»,12345678910»
52,NaN,NaN,NaN,NaN,NaN,NaN